export const GET_DATA_HOME = "home/GET_DATA_HOME";
export const GET_DATA_HOME_DETAIL = "home/GET_DATA_HOME_DETAIL";
export const GET_DATA_HOME_LOADING = "home/GET_DATA_HOME_LOADING";
export const GET_DATA_HOME_ERRORMESSAGE = "home/GET_DATA_HOME_ERRORMESSAGE";
