export const GET_DATA_NEWS = "news/GET_DATA_NEWS";
export const GET_DATA_NEWS_DETAIL = "news/GET_DATA_NEWS_DETAIL";
export const GET_DATA_NEWS_LOADING = "news/GET_DATA_NEWS_LOADING";
export const GET_DATA_NEWS_ERRORMESSAGE = "news/GET_DATA_NEWS_ERRORMESSAGE";
